# -*- coding: utf-8 -*-
"""GPU_Computing_PyCUDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vod9aFIzM_Ji0yWZqRt46PNyMt3VorJA
"""

!nvidia-smi

!pip install pycuda

import numpy as np
import time

N = 1000000

a = np.random.randn(N).astype(np.float32)
b = np.random.randn(N).astype(np.float32)

print("Arrays created successfully.")

start = time.time()

c_cpu = a + b

end = time.time()

cpu_time = end - start

print("CPU Time:", cpu_time)

import pycuda.driver as cuda
import pycuda.autoinit
from pycuda.compiler import SourceModule

mod = SourceModule("""
__global__ void add_vectors(float *dest, float *a, float *b)
{
    int idx = threadIdx.x + blockIdx.x * blockDim.x;
    dest[idx] = a[idx] + b[idx];
}
""")

a_gpu = cuda.mem_alloc(a.nbytes)
b_gpu = cuda.mem_alloc(b.nbytes)
c_gpu = cuda.mem_alloc(a.nbytes)

cuda.memcpy_htod(a_gpu, a)
cuda.memcpy_htod(b_gpu, b)

func = mod.get_function("add_vectors")

block_size = 256
grid_size = (N + block_size - 1) // block_size

start = time.time()

func(
    c_gpu,
    a_gpu,
    b_gpu,
    block=(block_size, 1, 1),
    grid=(grid_size, 1)
)

end = time.time()

gpu_time = end - start

print("GPU Time:", gpu_time)

c_result = np.empty_like(a)

cuda.memcpy_dtoh(c_result, c_gpu)

print("Results match:", np.allclose(c_cpu, c_result))

